//bpa pour bodypart antérieure
export const bpa = {
  tete: "Cap (ant.)",
  couG: "Gât (G)",
  couD: "Gât (D)",
  trapG: "Trapezul stâng",
  trapD: "Trapezul drept",

  epG: "Umarul stang (ant.)",
  epD: "Umarul drept (ant.)",
  biG: "Biceps stang",
  biD: "Biceps drept",
  coudG: "Cotul stâng (ant.)",
  coudD: "Cotul drept (ant.)",
  avbG: "Antebrațul stâng (ant.) (flexori)",
  avbD: "Antebrațul drept (ant.) (flexori)",
  poiG: "Incheietura stanga (ant.)",
  poiD: "Incheietura drept (ant.)",
  mainG: "Mâna stângă (ant.) (partea palmară)",
  mainD: "Mâna drept (ant.) (partea palmară)",

  pecG: "Pectoral stâng",
  pecD: "Pectoral drept",
  cotG: "Coastele stângi",
  cotD: "Coastele drepte",
  abdG: "Abdominalii stângi",
  abdD: "Abdominalii drepti",
  oblG: "Oblicuri stângi",
  oblD: "Oblicuri drepti",

  hanG: "Soldul stâng",
  hanD: "Soldul drept",
  quadG: "Cvadricepsul stâng",
  quadD: "Cvadricepsul drept",
  addG: "Abductorul stang",
  addD: "Abductorul drept",
  genG: "Genunchiul stâng (ant.)",
  genD: "Genunchiul drept (ant.)",
  tibG: "Tibia stângă",
  tibD: "Tibia dreapta",
  cheG: "Glezna stângă (ant.)",
  cheD: "Glezna dreapta (ant.)",
  pieG: "Piciorul stang",
  pieD: "Piciorul drept",
};

export const bpp = {
  tete: "Cap (post.)",
  trapG: "Trapezul stâng",
  trapD: "Trapezul drept",

  epG: "Umarul stang (post.)",
  epD: "Umarul drept (post.)",
  triG: "Triceps stang",
  triD: "Triceps drept",
  couG: "Cotul stâng (post.)",
  couD: "Cotul drept (post.)",
  avbG: "Antebrațul stâng (post.) (extensori)",
  avbD: "Antebrațul drept (post.) (extensori)",
  poiG: "Incheietura stanga (post.)",
  poiD: "Incheietura dreapta (post.)",
  mainG: "Mâna stângă (post.) (partea dorsală)",
  mainD: "Mâna dreapta (post.) (partea dorsală)",

  col: "Coloana vertebrală",
  scaG: "Regiunea scapulară stângă",
  scaD: "Regiunea scapulară dreapta",
  dosG: "Dorsal (flancul stâng)",
  dosD: "Dorsal (flancul drept)",
  lombG: "Lombar stâng",
  lombD: "Lombar drept",

  fesG: "Fesa stângă",
  fesD: "Fesa dreapta",
  iscG: "Ischio-jambierii stângi",
  iscD: "Ischio-jambierii drepti",
  genG: "Genunchiul stâng (post.)",
  genD: "Genunchiul drept (post.)",
  molG: "Gamba stânga",
  molD: "Gamba dreapta",
  cheG: "Glezna stângă (post.)",
  cheD: "Glezna dreapta (post.)",
  pieG: "Piciorul stang (post.)",
  pieD: "Piciorul drept (post.)",
};
